# Data Programming with Python
- Jan8 2018, Fan Li

## Part3

### Section I -- Arrays

1 - Write a Python program to convert a list and tuple into arrays.

In [1]:
import numpy as np

my_list = [1,2,3,4,5]
print("List to array:" + str(np.asarray(my_list)))

List to array:[1 2 3 4 5]


In [3]:
my_tuple = ([8,1,2], [1,2,3])
print("Tuple to array:" + str(np.asarray(my_tuple)))

Tuple to array:[[8 1 2]
 [1 2 3]]


In [4]:
my_tuple = (8,1,2)
print("Tuple to array:" + str(np.asarray(my_tuple)))

Tuple to array:[8 1 2]


2 - Write a Python program to create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3 - Write a Python program to reverse an array (first element becomes last).

In [11]:
x = np.arange(12,32)
print("Original:" + str(x))
x_inverse = x[::-1]
print("Inversed:" + str(x_inverse))

Original:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
Inversed:[31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


4 - Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.<br>
Sample Array [0, 12, 45.21 ,34, 99.91]

In [12]:
F = np.array([0, 12, 45.21 ,34, 99.91])
F_change = 5*F/9 - 5*32/9
print(F_change)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


5 - Write a Python program to find the real and imaginary parts of an array of complex numbers

In [13]:
x = np.sqrt([1+0j, 0+1j])
print(x)
print(x.real)
print(x.imag)

[ 1.00000000+0.j          0.70710678+0.70710678j]
[ 1.          0.70710678]
[ 0.          0.70710678]


6 - Write a Python program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [17]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
print(np.union1d(array1, array2))

[ 0 10 20 30 40 50 60 70 80]


7 - Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [18]:
print(np.diagflat([4,5,6,8]))

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


8 - Write a Python program to concatenate two 2-dimensional arrays. Sample arrays:<br>
([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

In [26]:
a = np.array([[0,1,3], [5,7,9]])
b = np.array([[0,2,4], [6,8,10]])
c = np.concatenate((a,b),axis=1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [27]:
a = np.array([[0,1,3], [5,7,9]])
b = np.array([[0,2,4], [6,8,10]])
c = np.concatenate((a,b),axis=0)
print(c)

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


9 - Create a null vector of size 10 but the fifth value which is 1

In [30]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


10 - Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [33]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*(3))
Z0[::4] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
