## Jan 9

In [1]:
fruit = "banana"
index = 0
while index < len(fruit):
    letter = fruit[index]
    index += 1
    print(letter)

b
a
n
a
n
a


In [2]:
for i in fruit:
    print(i)

b
a
n
a
n
a


In [3]:
print([w for w in fruit])

['b', 'a', 'n', 'a', 'n', 'a']


In [4]:
index = 0
result = list()
while index < len(fruit):
    letter = fruit[index]
    index += 1
    result.append(letter)
print(result)

['b', 'a', 'n', 'a', 'n', 'a']


In [5]:
res = list() #create/define new list
for i in range(0, len(fruit)):
    letter = fruit[i]
    res.append(letter)
print(res)

['b', 'a', 'n', 'a', 'n', 'a']


In [6]:
res = []  #another way to creat/define a new list
for i in range(0, len(fruit)):
    letter = fruit[i]
    res.append(letter)
print(res)

['b', 'a', 'n', 'a', 'n', 'a']


---

## Jan 10

In [1]:
ls

10_minutes_to_pandas.ipynb             Text mining with Python/
Book_learn Python3 the hard way.ipynb  UoE_ML Practical Labs_notebooks/
Data Programming with Python/          cs228-python-tutorial.ipynb*
SCRATCH NOTES.ipynb


In [2]:
ls

10_minutes_to_pandas.ipynb             Text mining with Python/
Book_learn Python3 the hard way.ipynb  UoE_ML Practical Labs_notebooks/
Data Programming with Python/          cs228-python-tutorial.ipynb*
SCRATCH NOTES.ipynb                    docs/


In [9]:
handle = open('./docs/test01.txt')
print(handle)

<_io.TextIOWrapper name='./docs/test01.txt' mode='r' encoding='UTF-8'>


In [10]:
counts = dict()
for line in handle:
    words = line.split()
    for word in words:
        counts[word] = counts.get(word, 0) + 1
print(counts)

{'this': 2, 'is': 1, 'a': 1, 'test': 1, 'for': 1, 'text': 1, 'in': 1, 'python': 1, 'list': 1, 'and': 1, 'the': 2, 'words': 2, 'are': 3, 'randomly': 1, 'created': 1, 'by': 1, 'me': 1, 'haha,': 1, 'good': 2, 'or': 1, 'not': 1, 'really': 1, 'depend': 1, 'on': 1, 'what': 1, 'you': 2, 'think': 1, 'about': 1, 'it.': 1, 'kidding': 1, 'me,': 1, 'yes': 1, 'i': 1, 'am.': 1, 'so': 1, 'let': 1, 'us': 2, 'just': 1, 'to': 1, 'do': 1, 'test.': 1}


In [11]:
lst = list()
for k,v in counts.items():
    print(k, v)

this 2
is 1
a 1
test 1
for 1
text 1
in 1
python 1
list 1
and 1
the 2
words 2
are 3
randomly 1
created 1
by 1
me 1
haha, 1
good 2
or 1
not 1
really 1
depend 1
on 1
what 1
you 2
think 1
about 1
it. 1
kidding 1
me, 1
yes 1
i 1
am. 1
so 1
let 1
us 2
just 1
to 1
do 1
test. 1


In [12]:
counts.items()

dict_items([('this', 2), ('is', 1), ('a', 1), ('test', 1), ('for', 1), ('text', 1), ('in', 1), ('python', 1), ('list', 1), ('and', 1), ('the', 2), ('words', 2), ('are', 3), ('randomly', 1), ('created', 1), ('by', 1), ('me', 1), ('haha,', 1), ('good', 2), ('or', 1), ('not', 1), ('really', 1), ('depend', 1), ('on', 1), ('what', 1), ('you', 2), ('think', 1), ('about', 1), ('it.', 1), ('kidding', 1), ('me,', 1), ('yes', 1), ('i', 1), ('am.', 1), ('so', 1), ('let', 1), ('us', 2), ('just', 1), ('to', 1), ('do', 1), ('test.', 1)])

In [32]:
for k,v in counts.items():
    lst.append((v, k))
unique_list = set(lst)
lst = sorted(unique_list, reverse = True)
print(lst)

[(3, 'are'), (2, 'you'), (2, 'words'), (2, 'us'), (2, 'this'), (2, 'the'), (2, 'good'), (1, 'yes'), (1, 'what'), (1, 'to'), (1, 'think'), (1, 'text'), (1, 'test.'), (1, 'test'), (1, 'so'), (1, 'really'), (1, 'randomly'), (1, 'python'), (1, 'or'), (1, 'on'), (1, 'not'), (1, 'me,'), (1, 'me'), (1, 'list'), (1, 'let'), (1, 'kidding'), (1, 'just'), (1, 'it.'), (1, 'is'), (1, 'in'), (1, 'i'), (1, 'haha,'), (1, 'for'), (1, 'do'), (1, 'depend'), (1, 'created'), (1, 'by'), (1, 'and'), (1, 'am.'), (1, 'about'), (1, 'a')]


In [37]:
for v,k in set(lst[:5]):
    print(k,v)

us 2
you 2
this 2
words 2
are 3


In [30]:
print(sorted([(v,k) for k,v in counts.items()], reverse=True))

[(3, 'are'), (2, 'you'), (2, 'words'), (2, 'us'), (2, 'this'), (2, 'the'), (2, 'good'), (1, 'yes'), (1, 'what'), (1, 'to'), (1, 'think'), (1, 'text'), (1, 'test.'), (1, 'test'), (1, 'so'), (1, 'really'), (1, 'randomly'), (1, 'python'), (1, 'or'), (1, 'on'), (1, 'not'), (1, 'me,'), (1, 'me'), (1, 'list'), (1, 'let'), (1, 'kidding'), (1, 'just'), (1, 'it.'), (1, 'is'), (1, 'in'), (1, 'i'), (1, 'haha,'), (1, 'for'), (1, 'do'), (1, 'depend'), (1, 'created'), (1, 'by'), (1, 'and'), (1, 'am.'), (1, 'about'), (1, 'a')]


In [38]:
for v,k in set(lst[:5]):
    print(k,v)

us 2
you 2
this 2
words 2
are 3


In [1]:
import numpy as np

print(np.arange(3,7,2))  #the last number here is the step size

[3 5]


In [2]:
a = np.array([[1,2], [3,4]])
print(a.flatten())

[1 2 3 4]


In [6]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = [1,2]
print(np.asarray(a))

[1 2]


In [10]:
print(np.array(a))

[1 2]


In [11]:
x = np.matrix( ((2,3), (3, 5)))
y = np.matrix( ((1,2), (5, -1)))
print(x*y)

[[17  1]
 [28  1]]


In [15]:
x = np.array( ((2,3), (3, 5)))
y = np.array( ((1,2), (5, -1)))
print(x*y)

[[ 2  6]
 [15 -5]]


In [16]:
x = np.array( ((2,3), (3, 5)))
y = np.array( ((1,2), (5, -1)))
print(np.dot(x, y))

[[17  1]
 [28  1]]


In [17]:
import pandas as pd
DataFrame = pd.read_csv('./docs/iris.csv', header = None)
print(DataFrame)

      0    1    2    3  4
0   5.1  3.5  1.4  0.2  1
1   4.9  3.0  1.4  0.2  1
2   4.7  3.2  1.3  0.2  1
3   4.6  3.1  1.5  0.2  1
4   5.0  3.6  1.4  0.2  1
5   5.4  3.9  1.7  0.4  1
6   4.6  3.4  1.4  0.3  1
7   5.0  3.4  1.5  0.2  1
8   4.4  2.9  1.4  0.2  1
9   4.9  3.1  1.5  0.1  1
10  5.4  3.7  1.5  0.2  1
11  4.8  3.4  1.6  0.2  1
12  4.8  3.0  1.4  0.1  1
13  4.3  3.0  1.1  0.1  1
14  5.8  4.0  1.2  0.2  1
15  5.7  4.4  1.5  0.4  1
16  5.4  3.9  1.3  0.4  1
17  5.1  3.5  1.4  0.3  1
18  5.7  3.8  1.7  0.3  1
19  5.1  3.8  1.5  0.3  1
20  5.4  3.4  1.7  0.2  1
21  5.1  3.7  1.5  0.4  1
22  4.6  3.6  1.0  0.2  1
23  5.1  3.3  1.7  0.5  1
24  4.8  3.4  1.9  0.2  1
25  5.0  3.0  1.6  0.2  1
26  5.0  3.4  1.6  0.4  1
27  5.2  3.5  1.5  0.2  1
28  5.2  3.4  1.4  0.2  1
29  4.7  3.2  1.6  0.2  1
..  ...  ...  ...  ... ..
70  6.5  3.0  5.8  2.2  3
71  7.6  3.0  6.6  2.1  3
72  4.9  2.5  4.5  1.7  3
73  7.3  2.9  6.3  1.8  3
74  6.7  2.5  5.8  1.8  3
75  7.2  3.6  6.1  2.5  3
76  6.5  3.2

In [18]:
DataArray = DataFrame.values
# or DataMatrix = DataFrame.as_matrix()
print(DataArray)

[[ 5.1  3.5  1.4  0.2  1. ]
 [ 4.9  3.   1.4  0.2  1. ]
 [ 4.7  3.2  1.3  0.2  1. ]
 [ 4.6  3.1  1.5  0.2  1. ]
 [ 5.   3.6  1.4  0.2  1. ]
 [ 5.4  3.9  1.7  0.4  1. ]
 [ 4.6  3.4  1.4  0.3  1. ]
 [ 5.   3.4  1.5  0.2  1. ]
 [ 4.4  2.9  1.4  0.2  1. ]
 [ 4.9  3.1  1.5  0.1  1. ]
 [ 5.4  3.7  1.5  0.2  1. ]
 [ 4.8  3.4  1.6  0.2  1. ]
 [ 4.8  3.   1.4  0.1  1. ]
 [ 4.3  3.   1.1  0.1  1. ]
 [ 5.8  4.   1.2  0.2  1. ]
 [ 5.7  4.4  1.5  0.4  1. ]
 [ 5.4  3.9  1.3  0.4  1. ]
 [ 5.1  3.5  1.4  0.3  1. ]
 [ 5.7  3.8  1.7  0.3  1. ]
 [ 5.1  3.8  1.5  0.3  1. ]
 [ 5.4  3.4  1.7  0.2  1. ]
 [ 5.1  3.7  1.5  0.4  1. ]
 [ 4.6  3.6  1.   0.2  1. ]
 [ 5.1  3.3  1.7  0.5  1. ]
 [ 4.8  3.4  1.9  0.2  1. ]
 [ 5.   3.   1.6  0.2  1. ]
 [ 5.   3.4  1.6  0.4  1. ]
 [ 5.2  3.5  1.5  0.2  1. ]
 [ 5.2  3.4  1.4  0.2  1. ]
 [ 4.7  3.2  1.6  0.2  1. ]
 [ 4.8  3.1  1.6  0.2  1. ]
 [ 5.4  3.4  1.5  0.4  1. ]
 [ 7.   3.2  4.7  1.4  2. ]
 [ 6.4  3.2  4.5  1.5  2. ]
 [ 6.9  3.1  4.9  1.5  2. ]
 [ 5.5  2.3  4.   1.

In [19]:
#Write a Python program to create a 2d array with 1 on the border and 0 inside

import numpy as np

x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
1 on the border and 0 inside in the array
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [20]:
#Write a Python program to test if specified values are present in an array.

import numpy as np

x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float)

print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

Original array:
[[ 1.12  2.    3.45]
 [ 2.33  5.12  6.  ]]
True
False
True
False
True


In [21]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
import numpy as np

x = np.arange(1, 100)

# find multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [25]:
import scipy.stats as sps

x = [5.05, 6.75, 3.21, 2.66] 
y = [1.65, 26.5, -5.93, 7.96]
(gradient,intercept,r_value,p_value,stderr) = sps.linregress(x,y) 
print ("Gradient & Intercept", gradient, intercept)
print ("R-squared", r_value**2)
print ("p-value", p_value)

Gradient & Intercept 5.3935773612 -16.2811279931
R-squared 0.524806275136
p-value 0.275564857882


___

## Jan 12

### Core NLP Tasks:
**Today:**
- Count words, counting frequency of words
- Finding sentence boundaries
- Part of speech tagging
- Parsing the sentence structure

**Latter:**
- Identifying semantic role labeling
- Named entity recognition
- Co-reference and pronoun resolution

In [11]:
file = open('./data/test01.txt')
print(file)

<_io.TextIOWrapper name='./data/test01.txt' mode='r' encoding='UTF-8'>


In [12]:
text2 = list()
for line in file:
    words = line.split()
    for word in words:
        text2.append(word)
print(text2)
file.close()

['this', 'is', 'a', 'test', 'for', 'text', 'in', 'python', 'list', 'and', 'the', 'words', 'are', 'randomly', 'created', 'by', 'me', 'haha,', 'the', 'words', 'are', 'good', 'or', 'not', 'good', 'really', 'depend', 'on', 'what', 'you', 'think', 'about', 'it.', 'are', 'you', 'kidding', 'me,', 'yes', 'i', 'am.', 'so', 'let', 'us', 'just', 'us', 'this', 'to', 'do', 'test.']


In [13]:
len(text2)

49

In [14]:
set(text2)

{'a',
 'about',
 'am.',
 'and',
 'are',
 'by',
 'created',
 'depend',
 'do',
 'for',
 'good',
 'haha,',
 'i',
 'in',
 'is',
 'it.',
 'just',
 'kidding',
 'let',
 'list',
 'me',
 'me,',
 'not',
 'on',
 'or',
 'python',
 'randomly',
 'really',
 'so',
 'test',
 'test.',
 'text',
 'the',
 'think',
 'this',
 'to',
 'us',
 'what',
 'words',
 'yes',
 'you'}

In [15]:
len(set(text2))

41

In [18]:
list(set(text2))

['just',
 'do',
 'python',
 'randomly',
 'yes',
 'for',
 'what',
 'not',
 'me',
 'in',
 'is',
 'i',
 'am.',
 'haha,',
 'or',
 'let',
 'created',
 'about',
 'good',
 'you',
 'really',
 'words',
 'to',
 'us',
 'test.',
 'depend',
 'kidding',
 'by',
 'think',
 'this',
 'the',
 'it.',
 'me,',
 'a',
 'text',
 'list',
 'and',
 'so',
 'on',
 'are',
 'test']

In [19]:
list(set(text2))[:5]  # the first 5 words

['just', 'do', 'python', 'randomly', 'yes']

In [25]:
import nltk

dist = nltk.FreqDist(text2)
len(dist)
dist.keys()

dict_keys(['this', 'is', 'a', 'test', 'for', 'text', 'in', 'python', 'list', 'and', 'the', 'words', 'are', 'randomly', 'created', 'by', 'me', 'haha,', 'good', 'or', 'not', 'really', 'depend', 'on', 'what', 'you', 'think', 'about', 'it.', 'kidding', 'me,', 'yes', 'i', 'am.', 'so', 'let', 'us', 'just', 'to', 'do', 'test.'])

In [29]:
dist[u'this']

2

In [32]:
self_define_choose_word = [w for w in dist.keys() if len(w) > 3 and dist[w] > 1]
self_define_choose_word

['this', 'words', 'good']

In [33]:
# normalization

input_text = "List listed lists listing listings"
word = input_text.lower().split(' ')
word

['list', 'listed', 'lists', 'listing', 'listings']

In [34]:
# stemming
porter = nltk.PorterStemmer()
[porter.stem(t) for t in word]

['list', 'list', 'list', 'list', 'list']

In [35]:
# lemmatization : stemming, but resulting stems are all valid words

udhr = nltk.corpus.udhr.words('English-Latin1')
udhr[:20]

['Universal',
 'Declaration',
 'of',
 'Human',
 'Rights',
 'Preamble',
 'Whereas',
 'recognition',
 'of',
 'the',
 'inherent',
 'dignity',
 'and',
 'of',
 'the',
 'equal',
 'and',
 'inalienable',
 'rights',
 'of']

In [36]:
# just stemming gives you non-valid words many sometimes
[porter.stem(t) for t in udhr[:20]]

['univers',
 'declar',
 'of',
 'human',
 'right',
 'preambl',
 'wherea',
 'recognit',
 'of',
 'the',
 'inher',
 'digniti',
 'and',
 'of',
 'the',
 'equal',
 'and',
 'inalien',
 'right',
 'of']

In [40]:
lemma = nltk.WordNetLemmatizer()
[lemma.lemmatize(t) for t in udhr[:20]]

['Universal',
 'Declaration',
 'of',
 'Human',
 'Rights',
 'Preamble',
 'Whereas',
 'recognition',
 'of',
 'the',
 'inherent',
 'dignity',
 'and',
 'of',
 'the',
 'equal',
 'and',
 'inalienable',
 'right',
 'of']

In [41]:
# Tokenization: splitting a sentence into words/tokens

text11 = "Children shouldn't drink a sugary drink before bed."
nltk.word_tokenize(text11)  # also have sent_tokenize()

['Children',
 'should',
 "n't",
 'drink',
 'a',
 'sugary',
 'drink',
 'before',
 'bed',
 '.']

In [42]:
# different from just split
text11.split(" ")

['Children', "shouldn't", 'drink', 'a', 'sugary', 'drink', 'before', 'bed.']

#### POS Tagging

![]('./pics/20180112_01.png)